apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      Name:
        type: string
        default: World
        description: Your Name
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Hello, ${{ inputs.Name }}"
          echo ""
          env
env:
  ENV1: TEST-env-PaRaM
