apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Private ECR Access
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    permissions:
      id-token: write
    steps:
      - name: Say hello
        uses: docker://377331541806.dkr.ecr.us-east-1.amazonaws.com/ddigtiar/ssh-agent:latest-jdk17
        shell: sh
        run: |
          echo "hello world"
          id
          env
